### PR TITLE
Added swedish translation

### PR DESCRIPTION
**Pull request by SlowNicoFish**
Created a new string values file for the swedish translation!
Feel free to change or deny if it's not good enough.

### CODE REVIEW

**Comment by m-i-n-a-r** [comment]
Thanks a lot! Before i merge this, just a couple questions: 
- I see some english remaining, for example at line 43: is that normal?
- You probably missed the string at line 44, for some reason it's disappeared :(

Apart from this, great work!

**Comment by SlowNicoFish** [comment]
Oh yes, something happened there. Will fix those!

**Comment by SlowNicoFish** [comment]
Now they should be fixed! :)

**Comment by m-i-n-a-r** [comment]
Ok, it seems perfect now! I'll double check tomorrow and i'll publish the update soon after (also updating the readme and the Play Store description to mention your contribution). Thanks again!

**Pull request merged**
