### PR TITLE
Latest fixes and features, v 3.1.0

### PR DESCRIPTION
**Pull request by m-i-n-a-r**

### CODE REVIEW

**Comment by DominikNovosel** [comment]
Working late at night, are we? 😄 I guess I should check the "awfully" translated new strings? Also, I think you forgot to update the Play Store description.

**Comment by m-i-n-a-r** [comment]
Yep. I published the update in a hurry because the search feature was broken in v3.0.3.
And yes, i have to update the play store description, I'll do it as soon as possible :)

**Comment by m-i-n-a-r** [comment]
@DominikNovosel If you want to review the strings and you have time, you can do it in the next few days, since i have to release a minor update to fix a bug regarding the theme change 😞

**Comment by DominikNovosel** [comment]
Will do!

**Pull request merged**
