### PR TITLE
Add basic GH Action

### PR DESCRIPTION
**Pull request by Paiusco**
I ~copied~ created the most basic workflow ~I could find on the internet~ to android apps. However, the build is failing on `master`. Is that an expected behaviour? That's pretty useful start point to be able to check if a PR is going to break the build.

### CODE REVIEW

**Comment by m-i-n-a-r** [comment]
Well it shouldn't fail, it compiles properly on my side, even if there are 2 or 3 incomplete features 🤔

**Comment by simonesestito** [comment]
The failing build may be caused by the fact that your branch @Paiusco is 12 commits behind m-i-n-a-r:master. Please, try merging with @m-i-n-a-r 's master branch, then retry executing the build.
I can see in logs (https://github.com/Paiusco/birday/runs/4718493397?check_suite_focus=true) that it fails because of the use of unallowed views in a layout file used as a RemoteView.
Also, this error got fixed here: https://github.com/m-i-n-a-r/birday/commit/3a76f94a89291e549d7f7fa487b0371e2a3ad327#diff-8c9ae70f89f169f3c3612e6ce4f83b082a95d9dbb7c7d14685334d8ada763da7L10

I can't see other issues Lint reported (it says there are 8 of them in total, and it logs only the first one, which is the TextView one I've just mentioned above).

**Comment by simonesestito** [comment]
@Paiusco It's because of lint errors, that don't allow the compilation to be successfully executed.
I'm currently working with @m-i-n-a-r to fix all those errors directly in the sources

**Comment by m-i-n-a-r** [comment]
@simonesestito @Paiusco an update: apparently, gradlew complains for any error, even non-fatal errors like missing translations. This is the output on my machine:

```
Lint found 12 errors and 28 warnings. First failure:
D:\Users\minar\Documents\Development\WorkspaceAndroid\birday\app\src\main\res\values\strings.xml:109: Error: "notification_only_favorites" is not translated in "ru" (Russian), "sv" (Swedish), "hu" (Hungarian), "cs" (Czech), "vi" (Vietnamese), "nl" (Dutch) [MissingTranslation]
    <string name="notification_only_favorites">Favorites only</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Lint found errors in the project; aborting build.
```

This means i have to find away to suppress those errors, since it's unlikely i will update every translation (i can't do this by myself except by using Google Translate, with awful results 😄 ). I'll see what i can do, but every suggestion is well appreciated.

**Comment by simonesestito** [comment]
You can simply add the following code inside your app/build.gradle file:

```
android {

    lintOptions{
        disable 'MissingTranslation'
    }

    //other build tags
}
```

**Comment by m-i-n-a-r** [comment]
Easier than I thought! done 🥳

**Comment by Paiusco** [comment]
I think now you can merge :smiley:

**Comment by m-i-n-a-r** [comment]
Yep i know, it's an incomplete feature, and is momentarily hidden 😃

**Pull request merged**
