### PR TITLE
Update PT-BR translation

### PR DESCRIPTION
**Pull request by Paiusco**
- Find all missing strings and translate them
- Update a few already translated

### CODE REVIEW

**Comment by Paiusco** [comment]
Please let me know if I missed any new string then I can update the PR

**Comment by m-i-n-a-r** [comment]
I'm about to add some new strings for the next update (it should take a week or two). I'll let you know when I'm done. In the meantime, thank you so much! You will be quoted in the readme and in the description obviously 🙂

**Comment by Paiusco** [comment]
Btw, it'd be a good idea to have a easy way to check in a language which strings are missing to be translated... It could even be a quick shell script

**Comment by m-i-n-a-r** [comment]
Yep, you're right, I'll see what i can do. I have no idea how to do it, but i'll try 😄 Regarding the new strings, they should be ready by the end of the week!

**Pull request merged**
