### PR TITLE
Added Serbian translation

### PR DESCRIPTION
**Pull request by Th3Unkn0wn0n3**

### CODE REVIEW

**Comment by Th3Unkn0wn0n3** [comment]
Just noticed that I've made a typo, county code for Serbia is rs not sr, can you fix it for me?

**Comment by m-i-n-a-r** [comment]
No problem, I'll take care of it! Thanks!

**Comment by m-i-n-a-r** [comment]
Just to let you know: the code for Serbian is sr, so you wasn't wrong. sr-RS is the code for Serbian, only valid in Serbia and not in other countries where Serbian is spoken 👍

**Comment by Th3Unkn0wn0n3** [comment]
Ok thanks, I didn't know that

**Comment by DominikNovosel** [comment]
Since Serbian is digraphic, what language code should be used to denote Latin Serbian? I might be able to help adapt your translation for the Latin writing system as well.

**Comment by Th3Unkn0wn0n3** [comment]
According to localeplanet code for cyrillic is sr_Cyrl, and for latin sr_Latn

**Comment by DominikNovosel** [comment]
Huh. That doesn't quite mesh with the current language designation of sr-RS. We also don't know whether this is how Android handles those locales.

**Comment by DominikNovosel** [comment]
Hmm... this might help: https://discuss.appium.io/t/how-to-set-device-locale-to-serbian-latin-in-android/26227

**Comment by m-i-n-a-r** [comment]
sorry for my ignorance of these languages, feel free to tell me if i have to fix something and how 🥲

**Comment by DominikNovosel** [comment]
No problem, we'll try to figure something out. I've been really busy lately though, so on the off-chance someone who is more familiar with this stumbles upon this app, I'll refer to this discussion in a new issue to make it more... visible.

**Pull request merged**
