### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by koterpillar**
This PR adds Russian translation for Birday.

Please note that I had to make changes to the code to account for the language complications which are described here:
* https://developer.android.com/guide/topics/resources/string-resource#Plurals
* https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals#List_of_Plural_Rules (search for "Russian", but also note how many variations are there)

This necessitated reworking some of the resources, where I had to partially apply this Commandment of Localisation: [Never Concatenate Strings](https://www.smashingmagazine.com/2012/07/12-commandments-software-localization/#2-never-concatenate-strings).

It would be nice for the other translators to take a look at the pluralised strings and see if a change is needed, however, all existing languages should see the exact same result as now.

~I've yet to test this on an actual device, will update if there are any problems.~

Tested on my device and fixed a few things I overlooked.

### CODE REVIEW

**Comment by m-i-n-a-r** [comment]
Thanks, i'll take a look at the commits and merge them. You will be credited of course!

**Comment by m-i-n-a-r** [comment]
Merged and credited (i'll also credit you in the app description on Play Store when possible). I just replaced the getResources() method with the kotlin property access .resources 👍

**Comment by DominikNovosel** [comment]
Wow, I see a lot of work went into making Birday fully translatable. Assuming the keywords now behave consistently with what is described in the Android developer guide (I couldn't read the code to make sure), this solves the problems I had translating Birday into Croatian, thanks.

**Comment by m-i-n-a-r** [comment]
Yep, it was a great contribution and the plurals in the russian translation are supported across all the languages available 😄

**Pull request merged**
