### PR TITLE
Fixed the blocked hint texts on two pages

### PR DESCRIPTION
**Pull request by yuhuitech**
Dear developer:

Hello! I am the creator of issue #74, and I have fixed the blocked hint texts on those two pages. I would appreciate it if you could kindly revise my code and leave me some advice. Thank you so much for your precious time!

Here are the screenshots after my changes:

copy copy

Thanks again! Have a nice day! :)

### CODE REVIEW

**Comment by franklinbill** [comment]
I met the same issue

**Comment by franklinbill** [comment]
Nice！I agree with your fix. @yuhuitech 👍

**Comment by franklinbill** [comment]
It seems that this issue is a11y. @yuhuitech

**Comment by m-i-n-a-r** [comment]
Thanks and sorry for being late :) I'm back to work now!

**Pull request merged**
