### PR TITLE
Update Croatian translation

### PR DESCRIPTION
**Pull request by DominikNovosel**
Noticed the Crowdin project halfway through, will continue there at some point.

### CODE REVIEW

**Comment by m-i-n-a-r** [comment]
Ok no problem, thanks a lot!

**Comment by DominikNovosel** [comment]
And I'll try to get to grips with Crowdin's workflow as soon as possible!

**Comment by m-i-n-a-r** [comment]
Ok, i updated Crowdin with every translation in this PR, thanks! Let me know if you need help with Crowdin 😄

**Comment by DominikNovosel** [comment]
Sure thing, thanks!

**Pull request closed without merging**
