### PR TITLE
add Catalan localization file

### PR DESCRIPTION
**Pull request by retiolus**

### CODE REVIEW

**Comment by m-i-n-a-r** [comment]
Thanks, appreciated!

**Comment by m-i-n-a-r** [comment]
Just a side note: part of the file is still in english! This isn't a problem for the app itself, but the translation will be just partial in this way. I'm also fixing some errors related to unescaped characters, i'll update the repo in minutes if you want to take a look and complete the translation 👍

**Comment by retiolus** [comment]
I intend to finish translating the file when I have a moment :)

**Comment by m-i-n-a-r** [comment]
No problem, i'll wait. Partial translation is better than no translation at all 😄

**Pull request merged**
